name: Gettext Updates
on:
  push:
    branches: master
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/gettext-template@master
      with:
        build-args: ELEMENTARY_CODENAME=next-unstable
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
